package theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF9F16B4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6FD)
val md_theme_light_onPrimaryContainer = Color(0xFF36003F)
val md_theme_light_secondary = Color(0xFF006970)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF7AF4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF002022)
val md_theme_light_tertiary = Color(0xFF6451A5)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE7DEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF1F005F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF24005B)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF24005B)
val md_theme_light_surfaceVariant = Color(0xFFEDDFE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFF6EDFF)
val md_theme_light_inverseSurface = Color(0xFF391E72)
val md_theme_light_inversePrimary = Color(0xFFFBABFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF9F16B4)

val md_theme_dark_primary = Color(0xFFFBABFF)
val md_theme_dark_onPrimary = Color(0xFF570065)
val md_theme_dark_primaryContainer = Color(0xFF7C008E)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FD)
val md_theme_dark_secondary = Color(0xFF4DD9E4)
val md_theme_dark_onSecondary = Color(0xFF00363A)
val md_theme_dark_secondaryContainer = Color(0xFF004F54)
val md_theme_dark_onSecondaryContainer = Color(0xFF7AF4FF)
val md_theme_dark_tertiary = Color(0xFFCDBDFF)
val md_theme_dark_onTertiary = Color(0xFF351F74)
val md_theme_dark_tertiaryContainer = Color(0xFF4C388C)
val md_theme_dark_onTertiaryContainer = Color(0xFFE7DEFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24005B)
val md_theme_dark_onBackground = Color(0xFFE9DDFF)
val md_theme_dark_surface = Color(0xFF24005B)
val md_theme_dark_onSurface = Color(0xFFE9DDFF)
val md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF24005B)
val md_theme_dark_inverseSurface = Color(0xFFE9DDFF)
val md_theme_dark_inversePrimary = Color(0xFF9F16B4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFBABFF)


val seed = Color(0xFFDE5CF0)
